### ISSUE TITLE
Docs theme: minor suggestions

### ISSUE THREAD

**Issue by Tzky** [SpongePowered/SpongeDocs#102]
I just had a look at the new Docs theme and now have some suggestions to improve it further:

-index (genindex.html) in the top right corner should be replaced with index.html
-prev and next isn't needed as we have a global toc and tracks
-update of the code snippets div to make it look like the Tips and Warnings div (no rounded edges, border-left:4px)
-the search button seems to be a tad off (1px too less height, 1px to the bottom)
-the toc might look better with a depth of only 2 (like the RtD Theme)

**Comment by hawtre** [comment]
The index link and search button are issues that should be fixed, but I disagree with the other two. 

The next/previous buttons are handy for skimming through the docs, since they're in a static position. They're also useful for going through different categories, such as from "Other Platforms" through to "Preparing for Development" and then back again. The navigation tree collapses, so you can't as easily click into the previous category. There's plenty of space for them anyway.

The rounded edges on the code snippet boxes are pretty subjective, but I'd much rather keep them as they are.

**Comment by Tzky** [comment]
I might add that the prev/next Buttons currently browse through the docs in alphabetical order. As long as this is not fixed the Buttons are pretty useless.

The rounded edges are very subjective, yes.

**Comment by gratimax** [comment]
> -index (genindex.html) in the top right corner should be replaced with index.html

yes it should, I will look into this

> update of the code snippets div to make it look like the Tips and Warnings div (no rounded edges, border-left:4px)

Done. I'm fine with either, but slightly prefer consistency in this case.

> -the search button seems to be a tad off (1px too less height, 1px to the bottom)

yeah. I fiddled with it so it displays correctly for me, but it's so fragile it breaks on any other screen resolution. I think I have a fix for that, though

> -the toc might look better with a depth of only 2 (like the RtD Theme)

One of the requirements I had to design the new theme was to keep the whole navigation in the sidebar, so no.

**Comment by BlackGoat** [comment]
@Tzky @gratimax Is there anything else to be done here, or can we close this issue?

**Comment by Tzky** [comment]
From my side this can be closed.

Index in the top right still points at genindex.html but i can't come up with a fix for this. Seems to be hardcoded in Sphinx to me.
